### ISSUE TITLE
Xagent variable defaultValue

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU#100]
The schema suggests that xagent variables can have `defaultValue` specified, however in the current implementation this is always `0`.

This should be a simple fix in `io.xslt`, but will also need adding for anywhere agents are created (from both the host and device).

**Comment by mondus** [comment]
Easy for device agent creation as variables are arguments and are explicitly set. Not the case for host agent creation. This needs investigating.

**Comment by mondus** [comment]
This has already been done on io.xslt. Probably when I fixed environment variables in initial states. Agent variable arrays can have only a scaler default value which is set to every element in the array. This is in line with the schema spec but probably not ideal. Possibly an enhancement if anyone ever needs this.
