### ISSUE TITLE
Support Vector types in Input/Output XML files.

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU#101]
Types such as `glm::vec2`, `glm::ivec3` (and `unsigned`) need to be supported in input and output of XML states.

A complete(ish) list of types which should be sorted are:

+ [ ] `unsigned int` - `%u`
+ [ ] `glm::vec2`, `glm::vec3`, `glm::vec4`
+ [ ] `glm::bvec2`, `glm::bvec3`, `glm::bvec4`
+ [ ] `glm::ivec2`, `glm::ivec3`, `glm::ivec4`
+ [ ] `glm::dvec2`, `glm::dvec3`, `glm::dvec4`
+ [ ] `glm::uvec2`, `glm::uvec3`, `glm::uvec4`
+ [ ] Possibly also matrix types?  i.e `glm::mat2` etc

i.e. see https://glm.g-truc.net/0.9.2/api/a00236.html

**Comment by mondus** [comment]
Relates to same issue as #114

**Comment by ptheywood** [comment]
Merged in #160 for release 1.5. Documentation is to be updated.
