### ISSUE TITLE
Segfault on invalid 0.xml path

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU#118]
When the path to the `iterations` file is incorrect, i.e. the parent directory of `0.xml`, the executable crashes with a segfault (under linux), rather than producing a useful error.

To address this, existence of the path and whether it is a file or directory should be checked prior to attempts to read from the file.

**Comment by ptheywood** [comment]
This appears to be linux only. 

Under windows this correctly errors with `Error opening initial states`. (23b1dca)

**Comment by mondus** [comment]
Need to check that input file is not a directory

https://stackoverflow.com/questions/4553012/checking-if-a-file-is-a-directory-or-just-a-file

**Comment by ptheywood** [comment]
Under linux directories are files, so fopen returns a valid file pointer. This is not the case on windows.

Unfortunately portable disk i/o in c between windows and linux doesn't really exist, so I've added a linux (non MSVC) specific fix using ifdefs.
