### ISSUE TITLE
Add Make target to generate functions.c

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU#133]
It is not clear to users how to get functions.c prototypes under linux.

We could simply add this as a new make target, which runs `xsltproc` on `functions.xslt` and produces `functions.c`, but not call this `functions.c` to avoid overwriting any work. 

Perhaps `functions_prototypes.c` or similar, or a file in the (untracked) `dynamic` folder. 
This would also need documenting clearly.

**Comment by mondus** [comment]
@ptheywood todo under #112

**Comment by ptheywood** [comment]
Closed by `009f822`.

`src/dynamic/functions.c` can be generated via `make functions.c` or `make src/dynamic/functions.c`.

As this is in the `src/dynamic` folder not `src/model`, it does not overwrite the users `functions.c` file, and is not used for compilation.
