### ISSUE TITLE
FLAMEGPU on ShARC docs: no mention that libxslt is dependency but not installed

### ISSUE THREAD

**Issue by willfurnass** [FLAMEGPU/FLAMEGPU#135]
See http://docs.hpc.shef.ac.uk/en/latest/sharc/software/libs/FLAMEGPU.html

Also, should these docs recommend using a particular git tag rather than the HEAD of master?

**Comment by ptheywood** [comment]
It appears `libxslt` is installed on Iceberg but not ShARC, so I assume these instructions are based on previous instructions for Iceberg?  ( @mondus )

The HEAD of master represents our latest release, with other branches / tags generally being WIPs.
The next major version which we are currently working on (1.5.0) will include improved linux support, although `xsltproc` and therefore `libxslt` will still be required.

On windows we ship `xlstproc.exe` with FLAME GPU (see the tools directory) but had found that `xsltproc` has typically been available by default on desktop linux distributions.

**Comment by ptheywood** [comment]
@willfurnass How do you suggest we resolve this? Do we request that `xsltproc` is made available on ShARC (as it is on icerberg) or do we simply update the documentation to point users to a compatible source of `xsltproc` to transfer to ShARC

We will also want to update the docs.hpc.shef.ac.uk site to reflect the instructions for building and using on sharc.

**Comment by ptheywood** [comment]
Having discussed this with Will, a request is being made for `xsltproc` to be installed on ShARC, as it is on iceberg.

**Comment by willfurnass** [comment]
The `libxslt` RPM, which provides `xsltproc`, will be rolled out across ShARC's worker nodes over the next hour or so.

**Comment by ptheywood** [comment]
Cheers @willfurnass. 

I have now verified that FLAME GPU examples can be built from the `release-1.5` branch via:

```
module load dev/gcc/4.9.4
module load libs/CUDA/8.0.44/binary

git clone git@github.com:flamegpu/flamegpu.git
cd flamegpu
git checkout release-1.5
cd examples/GameOfLife
make console
```

I have not tested the EXE runs, as no GPUs are currently available, but I am confident it will work. 

I'll close this issue, and add updating that document to the post-1.5 release tasks issue.
