### ISSUE TITLE
Makefile: Rebuild when flags are changed

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU#168]
Currently, if the makefile is changed so different flags are not used, the relevant files are not rebuilt. 

I.e if the user specifies `SMS` on the command line. 

It would be nice to make the Makefile aware of this. 

Possible approaches, each with advantages/limitations:

+ https://www.cmcrossroads.com/article/rebuilding-when-cppflags-changes
+ https://stackoverflow.com/questions/29877503/how-to-force-recompile-when-changing-makefile-flags

**Comment by willfurnass** [comment]
Making Makefile targets dependent on Makefile-set env vars makes sense.  Introducing fancy logic for rebuilding if externally-specified options differ from what's hard-coded in the Makefile seems like overkill.  FLAME is targeting people who most likely already know a bit of C so I'd consider what would be intuitive for them. 

How about just telling people if the first time they override vars on the command-line using particular values  then they need to run (IIRC) `make -B`?  Editing documentation is so much easier than editing Makefiles :)

**Comment by ptheywood** [comment]
Cheers @willfurnass, I've implemented this in fae33a3, #174

+ Non-phony makefile targets depend on `$(MAKEFILE_LIST)`, so if either the main makefile or the commonly included makefile have been changed, a rebuild is forced. 
+ The documentation for makefiles also now includes advice to use `make -B` when specifying new command line values.
