### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU#179]
Update the license

**Comment by ptheywood** [comment]
@mondus  Which licence are we intending to switch to? 

I would suggest a permissive licence such as:
+ [MIT](https://choosealicense.com/licenses/mit/)
   > A short and simple permissive license with conditions only requiring preservation of copyright and license notices. Licensed works, modifications, and larger works may be distributed under different terms and without source code.
+ [BSD 2-Clause](https://choosealicense.com/licenses/bsd-2-clause/)
    > A permissive license that comes in two variants, the BSD 2-Clause and BSD 3-Clause. Both have very minute differences to the MIT license.
+ [BSD 3-Clause](https://choosealicense.com/licenses/bsd-3-clause/)
    > A permissive license similar to the BSD 2-Clause License, but with a 3rd clause that prohibits others from using the name of the project or its contributors to promote derived products without written consent.


Or alternatively a slightly less permissive licence (if the above are to permissive) which provides trademark / patent related things
+ [Apache License 2.0](https://choosealicense.com/licenses/apache-2.0/)
    > A permissive license whose main conditions require preservation of copyright and license notices. Contributors provide an express grant of patent rights. Licensed works, modifications, and larger works may be distributed under different terms and without source code.

**Comment by ptheywood** [comment]
We will make this decision just prior to the 1.5 release.

**Comment by mondus** [comment]
MIT licence added and readme updated.
