### ISSUE TITLE
Multiple Spatial Partitions unsupported in agent_function

### ISSUE THREAD

**Issue by Robadob** [FLAMEGPU/FLAMEGPU#18]
If an agent function requires access to two spatially partitioned message lists, both parameters are named `partition_matrix` within `header.h`, meaning that compilation fails.

Noticed by Mozhgan.

Should be a quick fix;

a) Remove identifiers from the method prototypes
b) append `_<xsl-select....name()>` to the identifiers

The rarely used template for `functions.c` will likely also require updating.

**Comment by Robadob** [comment]
Note the above^ commit is in a feature branch, hopefully Mozhgan will be able to confirm/deny whether it works (or whether internal kernel launches also need adjusting).

**Comment by Robadob** [comment]
Turns out the FGPU schema forbids multiple message lists, so this feature may have been intentionally disabled under the guise of "if it's provided, they will use it (and it's probably not too efficient)".

It compiles using the fixes from the above branch, but I don't believe Mozhgan still requires it, so not really tested.

Will wait for @mondus to respond before closing with `wontfix`.

**Comment by mondus** [comment]
The schema forbids multiple message inputs per function on purpose to avoid overly complicated functions which are bad for performance. The correct method is to have separate functions for each input. Be careful with the feature branch @Robadob, what you have done might work for multiple spatially partitioned messages but it will almost certainly break when mixing message types.
