### ISSUE TITLE
Where to store the visualisation code in the project?

### ISSUE THREAD

**Issue by cmoralesmx** [FLAMEGPU/FLAMEGPU#180]
Hi,  
I created a custom visualization for my model based on the file `visualization.cu` produced by FLAMEGPU release-1.5. In the Visual Studio project, I store it as `visualization\myVisualization.cu`.  

Then, in order to compile the solution, I need to remove the file `dynamic\visualization.cu` from the project. This way, the compilation succeeds, the `dynamic\visualization.cu` is recreated every time I recompile. Its content is always the default code generated by FLAMEGPU but it doesn't conflicts with mine.  

Is this the usual behaviour? I checked the 'visualization.xslt' transformation is not enabled.
![image](https://user-images.githubusercontent.com/1790200/39133929-4925e644-470d-11e8-9a0a-95c70fcd0b44.png)

On the contrary, if I don't remove 'dynamic\visualization.cu' from the project, I get many conflicts due to duplicated functions, which is understandable.
![image](https://user-images.githubusercontent.com/1790200/39134316-475e552a-470e-11e8-8d07-83b71a1e4a99.png)

I guess I did things correctly because it works, but I prefer to ask.

**Comment by ptheywood** [comment]
@Robadob - I seem to recall you looking into the visual studio transformation rules being weird previously?

**Comment by Robadob** [comment]
@cmoralesmx 

In your attached screenshot you are modifying the setting for the `Release_Visualisation` configuration (visible in the top left drop down menu of the dialog). The console output you have screenshot includes the `-G` argument which is used to enable debugging information when building with nvcc

To me this suggests you are changing the release configuration whilst building the debug configuration.

Try changing the configuration drop down to `All Configurations` before changing that setting and rebuilding.

I'd appreciate it if you could confirm whether this is the case of not, before I investigate further.

**Comment by cmoralesmx** [comment]
@Robadob 
Sorry, I forgot to mention the file `visualisation.cu` is regenerated in both debug and release configurations even when `Tranform'visualisation.xslt enabled` value was already set to `no`.
![image](https://user-images.githubusercontent.com/1790200/39199777-34fa94e6-47e2-11e8-9aec-49f9121eff9f.png)  

![image](https://user-images.githubusercontent.com/1790200/39199806-4cd3e536-47e2-11e8-8f90-bbbf194f5b35.png)  

Anyway, I just applied the same setting for `All Configurations` and rebuild.
![image](https://user-images.githubusercontent.com/1790200/39200894-5186d360-47e5-11e8-8912-7418cbfa7fbf.png)


The output I got for Debug_Visualisation is here
https://gist.github.com/cmoralesmx/0bdb3971b5be86d603c1defb553f84a9

And for Release_Visualisation here
https://gist.github.com/cmoralesmx/74704bce8fe2967557788aee7bea2e0d

Both times the stock `visualisation.cu` was created in `dynamic`.
Just to clarify, it's not added back into the VS project, it's just recreated each time the project is rebuild.

**Comment by Robadob** [comment]
Yes, it appears clear what is occurring in your case.

I've just attempted to reproduce this with a fresh pull from the repo with the `CirclesPartitioning_float` example and failed (in both Visual Studio 2013 and 2015, you appear to be using 2013).

The only remaining idea I have is that your project properties are different to those of `XMLModelFile.xml`.

Can you confirm how the setting appears if you right click `XMLModelFile.xml` in the Solution Explorer and open properties from there? If that differs to project properties it will override the setting when the file is called to build.

**Comment by Robadob** [comment]
Those unresolved external symbols occur when you're building a configuration which includes a visualisation (whether default or custom).

You can either disable building of that file in console versions (right click the file, properties and select excluded from build=yes for each of the desired configurations), or tell it to link against `glew64.lib` and `glut64.lib` (this isn't included in non visualisation configurations by default).

*There might be an additional step to hook the visualisation code into a console project. Such as setting the compile time preprocessor macro `VISUALISATION`, however I'm not 100% sure that's necessary.*

**Comment by cmoralesmx** [comment]
Thanks!, I prefer including visualisation libraries in their respective configurations only. I disabled building the relevant file in console versions and that fixed the last issue.
