### ISSUE TITLE
Strange scaling issues on custom visualisation

### ISSUE THREAD

**Issue by cmoralesmx** [FLAMEGPU/FLAMEGPU#182]
I am using branch "release-1.5" of FLAMEGPU to implement a particles physics model.  
I took the stock `visualization.cu` file as the basis for [my custom visualization](https://github.com/cmoralesmx/FLAMEGPU/blob/EV_boundaries/examples/ExtracellularVesiclesDiffusion/src/visualisation/myVisualisation.cu)  

*Note:* As the needs of the model call for visualising the physical boundaries of the system and OpenGL concepts are still somewhat mystical for me, there may be fundamental mistakes in my approach, please bear with me.

Firstly, in order to have the boundaries displayed, I modified the `display()` function as follows.   

Right after the loop where the agents are rendered, I added:  

https://github.com/cmoralesmx/FLAMEGPU/blob/da35a33a83b24cae9620dc1fb158ed784784d8aa/examples/ExtracellularVesiclesDiffusion/src/visualisation/myVisualisation.cu#L645-L657  

(I am manually including the code here as the preview was not showing the embeded code)

```C
	glUseProgram(0);

	glLineWidth(2.5);
	glColor3f(0.0, 0.0, 0.0);
	glBegin(GL_LINE_STRIP);

	glVertex3f(offset_x/2 - 50.0, offset_y/2 + 50.0, 0.0);
	glVertex3f(offset_x/2 - 50.0, offset_y/2 - 50.0, 0.0);
	glVertex3f(offset_x/2 + 50.0, offset_y/2 - 50.0, 0.0);
	glVertex3f(offset_x/2 + 50.0, offset_y/2 + 50.0, 0.0);
	glVertex3f(offset_x/2 - 50.0, offset_y/2 + 50.0, 0.0);
	glEnd();
	glUseProgram(shaderProgram);
```

The following screenshot suggests this naive approach seems to work correctly. 

![flame_01_correct](https://user-images.githubusercontent.com/1790200/39140437-76a97234-471c-11e8-9257-4ae231ae78d6.PNG)
Here, you are looking at a 200 um by 200 um shape where some agents are randomly positioned within the range (-97,97) for both 'x' and 'y'. The goal was to represent 1um as 1 pixel at the default settings of the visualisation.

Then, as the iterations progress, I can see the visual representation of the boundaries matches the values used in the simulation. The following screenshot shows a close-up of a corner of the same shape. The visual representation seems to be correct.  

![flame_02_correct_boundaries](https://user-images.githubusercontent.com/1790200/39140512-b46d504a-471c-11e8-8925-dba8e1b17476.PNG)  

However, the issue arises after switching to an initial states file where all the agents are located at the origin. The following screenshot shows such system after it loads the initial states.  

![flame_03_at_origin_s0](https://user-images.githubusercontent.com/1790200/39140592-f7f7bd3c-471c-11e8-95b2-9aad2603d710.PNG)  
In the screenshot, I have signalled all the agents correctly located at the origin.  

Then, after a single iteration, the position of the agents changes massively. They are supposed to displace less than 0.5 um per iteration which would be less than a pixel. But somehow, on the second iteration, the agents are rendered all over the window, when their coordinates should be within [-1,1]. This can be seen in the following screenshot.  
![flame_04_at_origin_s1_error](https://user-images.githubusercontent.com/1790200/39142120-a173ee9a-4721-11e8-86a0-d065723e05f9.PNG)  

After that scaling, the displacement seems to occur according to what is implemented.  

Somehow, it seems OpenGL takes the coordinates of the agents within [-1,1] as if their values were already clamped to OpenGL's [-1,1] range and renders them in a kind of scaled-up position.  

This scaling, however, seems to be occurring in the buffer used for CUDA and OpenGL interop, and this scaling messes up further computations because at iteration 2 some agents are located anywhere between [-99, 99] (and some of them even further away).  

Just to clarify, this behaviour only affects the visualization, as the command line simulation computes the correct values correctly.  

Any help would be greatly appreciated.

**Comment by ptheywood** [comment]
Would you be able to provide the culprit initial states file for your model? 

XML files are blocked by .gitignore to avoid tracking output files, so you may need to use `git add -f path/to/0.xml` to add it to your repository. 

After a quick look at your functions.c file, I think there *may* be an issue in the computation of the calculation of `vp1` and `vp2` in `ev_collision_resolution` (https://github.com/cmoralesmx/FLAMEGPU/blob/da35a33a83b24cae9620dc1fb158ed784784d8aa/examples/ExtracellularVesiclesDiffusion/src/model/functions.c#L305-L347).

If you are creating all agents at `0.0f, 0.0f`, the value of `message->distance` will be `0.0f`. 
This is then used to calculate the value of `cs` and `sc` as the divisor, resulting in division by 0. 
These values are then used to calculate positions and velocities, which may results in larger than expected movements.

If you can provide an initial states file I'm happy to look into this further.

**Comment by cmoralesmx** [comment]
@ptheywood 
To prevent zero divisions I tested adding `FLT_MIN` (from `float.h`, with a value of 1E-37) to each division in `ev_collision_resolution`. However, the visual issue persists.  

Instead of pushing the 0.xml to the repo, I uploaded one with 64 agents here https://gist.github.com/cmoralesmx/67ffc75fbe11d6de46782440a684cdca

I am missing mentioning a relevant detail, the first step is precomputed outside of FLAME by a script which generates the 0.xml file. This is so because each agent keeps track of its previous position in `agent->x_1, agent->y_1`. So, the agent's initial positions in FLAMEGPU are not exactly (0,0) but still very close to the origin, as you will see in the 0.xml file.  
The script that creates the 0.xml file uses the same equations I have in the FLAMEGPU model.

**Comment by ptheywood** [comment]
@cmoralesmx 

Using the 64 agent initial file above, a single iteration results in the following, as of `da35a33`

![image](https://user-images.githubusercontent.com/628937/39477960-ca27dc6a-4d58-11e8-9963-70036eec0792.png)

Both `Release_Console` and `Release_Visualisation` builds show the same x/y values after a single iteration.

Assuming that this is the incorrect behaviour being observed (just not to the degree as in your image above) I believe that this is a result of the `ev_collision_resolution` agent function.

If I remove the body of the `ev_collision_resolution` agent function, then agents barely move - they travel at their velocity and are not near the walls so there are no collisions.

![image](https://user-images.githubusercontent.com/628937/39478073-2845ca28-4d59-11e8-84a0-b3bf9351ef40.png)

With this initial states file, I recorded the value of each agents `x`, `y`, `vx` and `vy` at the start and end of `ev_collision_resolution`, which shows the following changes.

  | x | y | vx | vy
-- | -- | -- | -- | --
min delta | -13.9306 | -8.8844 | -0.81893 | -1.46756
max delta | 6.667697 | 7.948905 | 1.485333 | 1.592782
mean delta | -0.50256 | 0.103984 | 0.055302 | -0.04535

Large jumps then continue for a few agents for several more iterations, until agents stop colliding.

The agent with `id` `14` has the largest change in `x` of `-13.9306`, from `-0.00477` to `-13.935321` with a vx from `-1.6984` to `-1.814673`, and had collided with agent `13`.

I'm not sure I fully understand this agent function is doing however there are two points which look like potential issues to me:

One possibility is that collisions can be resolved twice, if the colliding agents are the closest to each other. 
I.e if agent 13 output a message stating it collided with agent 14, and agent 14 output  a message stating that it collided with agent 13 then agent 14 would update it's values based on the collision with agent 13 twice.


The second possibility is that the value of `ddt` (although I'm not 100% confident in the agent functions' behaviour).

I've also been looking at individual values to see why larger changes in x and y have occurred than expected, without fully understanding the purpose of each variable.
From the above comments it appears that you expect movement of less than  `0.5 um` per iteration, where `um` is the unit of the floating point values `x` and `y` (The are highlighted in the visualisation is `-100` to `100`. 

For agent 14 in provided example, which collides with agent 13:
when `message->ev1_id == agent->id`, and the elseif condition has been disabled for simplicity, variables have the following values: 

| variable | value | variable | value |
|----------|-------|----------|-------|
| message->ev1_id |  14 |  cs | -0.922766 | 
| message->ev2_id |  13 |  sc | -0.385360 | 
| message->distance |  0.000381 |  vp1 | 1.670888 | 
| message->ev1_mass |  0.000000 |  vp2 | 1.806964 | 
| message->ev1_r_um |  0.145000 |  dt | 0.002500 | 
| message->ev1_x |  -0.004766 |  ddt | -1.981382 | 
| message->ev1_y |  -0.000755 |  dist | 0.000381 | 
| message->ev1_vx |  -1.698400 |  dx | -0.000352 | 
| message->ev1_vy |  -0.269000 |  dy | -0.000147 | 
| message->ev2_mass |  0.000000 |  distance | 0.000381 | 
| message->ev2_r_um |  0.125000 |  ax | -0.922766 | 
| message->ev2_x |  -0.005118 |  ay | -0.385360 | 
| message->ev2_y |  -0.000902 |  va1 | 1.670888 | 
| message->ev2_vx |  -1.823898 |  vb | -0.406271 | 
| message->ev2_vy |  -0.321602 |  va2 | 1.806964 | 
| dmin | 0.270000 |  vaP | 1.796893 | 

To me, the most likely culprit for the larger than expected movement is `ddt`, which is used as a multiplier throughout the function.
I would guess that `ddt` should never be less than `-dt`? as this is effectively responding to collisions which occurred before the iteration? This assumption may well be wrong.

`ddt` is used to modify `x` and `y` for the agents:
```
agent->x -= message->ev1_vx * ddt; // ev1 - agent->x
agent->y -= message->ev1_vy * ddt;
// ...
agent->x += agent->vx * (dt - ddt);
agent->y += agent->vy * (dt - ddt);
```


Does this help at all?
