### ISSUE TITLE
Migrating models from NetLogo to Flame GPU

### ISSUE THREAD

**Issue by antonst** [FLAMEGPU/FLAMEGPU#184]
I recently started using Flame GPU and I am very intrigued by its capabilities! I completed a tutorial and now I have a number of questions, which unfortunately I was not able to answer while reading Flame GPU documentation. I have used NetLogo and would like to migrate some for the models from NetLogo to Flame GPU.

1. NetLogo has four agent types: turtles, patches, links and observer. Turtles correspond to agents in Flame GPU, but I could not find anything which would correspond to patches (stationary agents: Each patch is a square piece of “ground” over which turtles can move) and links (Every link has two ends, and each end is an agent). I would appreciate any help in defining those agents in Flame GPU.

2. NetLogo allows to specify the size of the world in terms of the number of patches. In Flame GPU world is limited by lower and upper bounds, e. g. (-1,1). I could not find any recommendations on how to set up the world in Flame GPU. In many cases the size of the world would affect behavior of the model.

3. Is it possible to automatically limit the number of neighbors for communication? For example, communicate with only 4 neighbors, or 8 neighbors.

**Comment by antonst** [comment]
Answers by Dr. Richmond:

1. There is the idea of discrete agents in FLAME GPU. These represent the equivalent of patches in NetLogo. Check out the pedestrian navigation example and Game of Life for an example of how these work. They essential are agents which act like a cellular automaton and can communicate with mobile agents using messages. There are some specific restrictions in this type of agent such as having power of two dimensions and only 2D environments. Check out the docs in the relevant section.

2. With discrete agents the width/height represents an integer number of cells (patches). You will need to manually convert your environment for your spatial agents into a relevant position in the 2D grid. Again see the pedestrian navigation example to see how this is done.

3. Communication for mobile agents is spatial in which case message within the spatial radius will be considered. You can within your agent function choose to limit the messages which are used to update values to achieve a limit on the level of information which is considered.

**Comment by mondus** [comment]
Hi @antonst are you happy with the reply? Can this request for help be closed?

**Comment by ptheywood** [comment]
> Thank you for the info! I don't understand what you mean by power of two dimensions. Is this related to the number of discrete agents? 

The buffer size for discrete agents must be a power of two number that can be decomposed into a square grid. I.e. 1024 corresponds to a 32 x 32 grid from the documentation
> For discrete agents the bufferSize is strictly limited to only power of 2 numbers which have squarely divisible dimensions (i.e. the square of the bufferSize must be a whole number).
> http://docs.flamegpu.com/en/latest/flamegpu/modelspec.html#defining-an-x-machine-agent


> What should I do if my model is 3D? Can I use mobile agents which remain stationary for the entire step to simulate patches?

Discrete agents in FLAME GPU are limited to 2D environments only. Instead, as you've suggested, you should use `continuous` agents which do not modify their `x`, `y` and `z` properties. 

> In first case I am getting inconsistent state updates for the agents. For example, if I try to update agent's memory based on some condition (value of the variable), agent memory gets updated for most agents, but not for all of them after iteration is finished. Let's say I have a total of 100 cell agents and only for 20 of them variable occupied is set to 0. Inside a function I update cell agent's color variables based on condition: if (xmemory->occupied == 0). When I plot data from XML, color for 16 agents is changed. Can this be related to the fact, that I am returning 0 after the condition is satisfied, instead of returning 0 at the end of the function?

Returning 0 mid function may impact behaviour if you are doing so within a message iteration loop - threads cooperatively transfer data into shared memory which may be impacting behaviour. If it is not within a message loop (I don't think it is) I'm not 100% sure why this would be the case. I would need to have closer look at the relevant code and XML file. 

> I have a related question: Is it possible to have communication between subsets of agents? For example we have 80 atom agents and 100 cell agents and we want to implement communication between 20 cell agents and 80 atom agents, or between 80 cell agents and 10 atom agents. Is this possible? In case if we have two types of mobile agents, is communication between them always all-to-all?

Currently there are 3 message partitioning strategies which limit communication (see http://docs.flamegpu.com/en/latest/flamegpu/modelspec.html#defining-messages). 

+ Non Partitioned Messages
+ Discrete Partitioned Messages
+ Spatially Partitioned Messages

Discrete and Spatially partitioned messages restrict communication to local agents for discrete and continuous agents respectively. 
I.e. for your example of two continuous agents, you can restrict communication to a spatial radius using spatially partitioned messaging. This will (potentially) reduce the number of messages each agent must iterate, improving performance.

> I am also curious how message lists are implemented. Documentation says that list ends with NULL. if I use while(message) sometimes simulation gets stuck in first iteration. Replacing while with a for loop resolves the issue. I don't understand why this is the case.

Messaging is designed to work with a `while` loop, as demonstrated in the example models.
https://github.com/FLAMEGPU/FLAMEGPU/blob/master/examples/Boids_BruteForce/src/model/functions.c#L99-L132

I.e for a message of name `location`
```
xmachine_message_location* location_message = get_first_location_message(location_messages);
while(location_message) {
    // Access message variables
    if (location_message->id != xmemory->id){
          // ...
    }
    
    location_message = get_next_location_message(location_message, location_messages);
}
```

The use of the `get_first_*_message` and `get_next_*_message` are both necessary, and all threads in the block must execute these functions (ie do not `return` within a message loop).

I'm not sure why this would get stuck in the first iteration.
Out of interest, what OS, CUDA version and GPU are you using?

**Comment by mondus** [comment]
@antonst Are you happy with this response? I would like to close this issue.

**Comment by antonst** [comment]
@ptheywood thank you very much for your reply! I have successfully implemented Solid Diffusion model from NetLogo in Flame GPU. 

> The buffer size for discrete agents must be a power of two number that can be decomposed into a square grid. I.e. 1024 corresponds to a 32 x 32 grid from the documentation

Got it! Thanks.

>Discrete agents in FLAME GPU are limited to 2D environments only. Instead, as you've suggested, you should use continuous agents which do not modify their x, y and z properties.

Understood.

> Returning 0 mid function may impact behaviour if you are doing so within a message iteration loop - threads cooperatively transfer data into shared memory which may be impacting behaviour. If it is not within a message loop (I don't think it is) I'm not 100% sure why this would be the case. I would need to have closer look at the relevant code and XML file.

I think was getting "inconsistent" state updates due to small buffer sizes for messages. 

> Currently there are 3 message partitioning strategies which limit communication (see http://docs.flamegpu.com/en/latest/flamegpu/modelspec.html#defining-messages).

Non Partitioned Messages
Discrete Partitioned Messages
Spatially Partitioned Messages
Discrete and Spatially partitioned messages restrict communication to local agents for discrete and continuous agents respectively.
I.e. for your example of two continuous agents, you can restrict communication to a spatial radius using spatially partitioned messaging. This will (potentially) reduce the number of messages each agent must iterate, improving performance.

Thanks for the info!

> Out of interest, what OS, CUDA version and GPU are you using?

CentOS Linux release 7.4.1708 (Core)

Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

NVIDIA Tesla P100-PCIE

**Comment by antonst** [comment]
I have a few related questions:

 * is it possible to write an xml file with agent states every 100 iterations? Writing this file every iteration significantly adds to runtime.

 * is it possible to define a condition inside an agent function which would allow to stop the simulation? 

 * when increasing the size of the 3D model there are cases when I am running out of memory. Currently I am able to run 1000000 agents. I know this really depends on the model and message sizes, but what are the possible solutions to run models with more than 1000000 agents with Flame GPU?

**Comment by ptheywood** [comment]
> is it possible to write an xml file with agent states every 100 iterations? Writing this file every iteration significantly adds to runtime.


This is not possible in the current release, however in the upcoming 1.5 release you will be able to access agent data in step and exit functions (see #178) through some new functionality, which will allow you to produce your own output files. 
However, adding a simple flag to output every N iterations would potentially be relatively simple which I will look into adding (See #218)

> is it possible to define a condition inside an agent function which would allow to stop the simulation?

There is currently **no safe way to do this**. 
As of 1.5.0 you would be able to do this in an **unsafe** way (ie no memory deallocation, no exit functions) by accessing agent data on the host (#178) and if some condition is met calling `exit(EXIT_SUCCESS)` in an `STEP` function. Alternatively one of the included analytics functions (`count`, `reduce`, `min`, `max`, see #215) would perform a reduction over all agents in a given state list and return a value used to check if you should call exit or not. This would likely perform better (parallel operation and less Device to Host memcpy).

> when increasing the size of the 3D model there are cases when I am running out of memory. Currently I am able to run 1000000 agents. I know this really depends on the model and message sizes, but what are the possible solutions to run models with more than 1000000 agents with Flame GPU?

As you state the population size is limited on the model and messages sizes. The more variables each agent or message has the more memory is required. Additionally the more states you may have the more memory is required. 
If you cannot reduce the above, the only option is to find a GPU with more memory. The P100 you are running on currently is a 16GB card, the only larger options are some quadros with 24GBs or Tesla V100 and Quadro GV100 which now come in 32GB variants.

We are aware of this limitation and it is one aspect we intend to support with FLAME GPU 2.X in the future.

**Comment by antonst** [comment]
> This is not possible in the current release, however in the upcoming 1.5 release you will be able to access agent data in step and exit functions (see #178) through some new functionality, which will allow you to produce your own output files. However, adding a simple flag to output every N iterations would potentially be relatively simple which I will look into adding (See #218) Edit: This has been implemented in #219 so should be available in the 1.5.0 release.

Awesome! When version 1.5.0 will be available?

>There is currently no safe way to do this. As of 1.5.0 you would be able to do this in an unsafe way (ie no memory deallocation, no exit functions) by accessing agent data on the host (#178) and if some condition is met calling exit(EXIT_SUCCESS) in an STEP function. Alternatively one of the included analytics functions (count, reduce, min, max, see #215) would perform a reduction over all agents in a given state list and return a value used to check if you should call exit or not. This would likely perform better (parallel operation and less Device to Host memcpy).

OK, got it. Thank you for the info!

>As you state the population size is limited on the model and messages sizes. The more variables each agent or message has the more memory is required. 

I understand this is the case for agents, but I don't understand why the number of messages affects amount of memory we need to allocate. Can you please explain in more detail? I also don't understand how to correctly count messages. For example if I have 100 agents and each of them sends a single Discrete Partitioned Message which is received with radius = 1. How large should the buffer be? 100 or 900? 

> Additionally the more states you may have the more memory is required. If you cannot reduce the above, the only option is to find a GPU with more memory. The P100 you are running on currently is a 16GB card, the only larger options are some quadros with 24GBs or Tesla V100 and Quadro GV100 which now come in 32GB variants.

Thank you for the info.

**Comment by ptheywood** [comment]
> Awesome! When version 1.5.0 will be available?

We're hoping to get the release out in the next few weeks. 

> I understand this is the case for agents, but I don't understand why the number of messages affects amount of memory we need to allocate. Can you please explain in more detail?

Messages are stored in separate device memory to agent data. For each message type there is a struct of array allocated for `bufferSize`  elements. I.e if we have a message containing 8 integer values (4 bytes each) and a buffer size of 1024 then that message list requires `32kB` of device memory. More messages and larger messages require more memory. 

>  I also don't understand how to correctly count messages. For example if I have 100 agents and each of them sends a single Discrete Partitioned Message which is received with radius = 1. How large should the buffer be? 100 or 900? Assuming 2D grid.

Each message is only stored once, so (generally speaking) you want the message list bufferSize to be the same as the population which outputs that message. 
There are cases where you would want a larger bufferSize than any single population size (for instances where multiple agent functions output to the same message list (in different layers)) but generally using the same bufferSize is sufficient.

**Comment by antonst** [comment]
Thank you! This is very helpful.

**Comment by mondus** [comment]
@antonst 1.5 is released this week. I am closing this issue but feel free to open another one if you have further questions.
