### ISSUE TITLE
Allow visualisation modes to call xml exitFunctions

### ISSUE THREAD

**Issue by coolmule0** [FLAMEGPU/FLAMEGPU#239]
On exiting visualisation, would be useful to have exit functions called to do e.g. writing to files

**Comment by mondus** [comment]
Technically a bug.

**Comment by ptheywood** [comment]
I've looked into implementing this in the past, however the version of freeglut used does not allow for a callback function to be attached to the closing of the window.

We may be able to switch to a more recent freeglut implementation which does implement `glutCloseFunc` to call exit functions when the window is closed. 

Alternatively the keybind for escaping (`Esc` or `q`) could be modified to also call exit functions.
