### ISSUE TITLE
Project creation / Empty Project

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU#24]
Creating a new model generally involves taking an existing model and stripping out the details.

Providing an empty example would simplify this process.

Another option would be to add the relevant VS commands to create a new project of the sort.

Projects outside of the `examples` folder for independent git repos would be nice too.

**Comment by Robadob** [comment]
[This](https://msdn.microsoft.com/en-us/library/bb166376.aspx) seems to be the guide on creating custom project types.

**Comment by mondus** [comment]
There always used to be an empty project in older versions of FLAME GPU. Not sure where it went. A simple empty project would be sensible to add. I doesn't need a fancy new project type just an empty minimal FLAME GPU example called template for people to easily extend.
