### ISSUE TITLE
Allow early exit of simulation

### ISSUE THREAD

**Issue by coolmule0** [FLAMEGPU/FLAMEGPU#240]
Allow users to end the simulation early, irrespective of the remaining number of iterations specified in the command-line input. 

As an extension, allow infinite iterations in console mode under the assumption the user has created a call to exit the simulation at some point

**Comment by mondus** [comment]
This would be fairly easy to integrate. Suggest a host function called `exit_early()` which would just break the main iterations loop and then preserve any behaviour with XML writing.
