### ISSUE TITLE
Some questions about FLAMEGPU

### ISSUE THREAD

**Issue by CiaranWelsh** [FLAMEGPU/FLAMEGPU#246]
Hi, 

I have been experimenting with FLAMEGPU. I think its a great piece of software and I'm looking forward to seeing some simulations from it. I have a few questions that weren't quite clear from the docs and I was hoping you'd be able to answer them. If you are interested, my project so far is available <a href="https://github.com/CiaranWelsh/SenescenceModel">here</a>. I have designed the model and implemented a first stab, but I imagine there is a bit more development to go. 

<h2>Question 1</h2>
When creating an agent as part of a function using xagentOutput (line `477` of `senescence_model/src/model/functions.c` in my repo), how do you ensure the new agent has a unique `id` variable? At the moment I've just given the new agent the same id as the new one which probably will not work. 

<h2>Question 2</h2>
Is it possible to have a function which has both input and outputs? If not then it would be good to note this in the docs.

<h2>Question 3</h2>
I'm not quite clear about exactly how to use to use the random number generator. I've use `rnd<CONTINUOUS>(rand48)` in my code, as suggested in the docs, but this looks unusual to me (who is new to c++). Since I do not have an error on compile I'm guessing this is not a syntax error but can you confirm that this is the correct way to use the random number generator? Also, it is not clear what type of random number this is. I have assumed its uniform random between 0 and 1 which I need for probabilities, but this is only based on looking at how its used in the keratinocyte example. Is this the case. Also, is there support for drawing random numbers from other distributions, i.e. normal?

<h2>Question 4</h2>
Do you have more detailed information about how I can build a custom visualization. The docs are a bit vague on this, at least to somebody new to OpenGL. What I want to achieve is quite simple. I have 2 agents, TissueBlock and Fibroblast. The Tissue block represents the dermis which are meant to be cubes while fibroblasts are simple spheres, like agents in the examples. The TissueBlock agents should be coloured darker depending on the amount of damage while fibroblasts in different states would be different colours. I have began learning OpenGL but its quite a large topic. I'd really appreciate it if you would give me some pointers in how to a custom visualisation. 

<h2>Question 5</h2>
Is it possible to specify a folder for the many xml files running a simulation via the console generates? There does not seem to be an option in the console.exe help output. 

Thank you in advance for the help, all the best

Ciaran Welsh
Newcastle University

**Comment by ptheywood** [comment]
Hi,

### Question 1

Unfortunately we do not provide a method of generating a unique ID for device-generated agents, although it is probably a common issue.
If you are familiar with CUDA at all it would be feasible to implement this using an `atomicInc` operation on a globally accessible device variable to keep get the next unique integer, up to some maximum threshold. I'll create a new issue as this is probably worth implementing in general.

### Question 2 

Agent functions can both input and output to message lists. These must be specified in the correct order, with the `<inputs>` being prior to the `<outputs>` tag. 

### Question 3 

The random number generation in FLAME GPU 1 pre-dates the now-popular curand library. As such it is quite limited in that it can only sample from the uniform distribution, returning a floating point number between `0.0f` and `1.0f` inclusive. The function `rnd` takes the `rand48` as a parameter to ensure that each thread is sampling from it's own random number distribution, with different seeds to other threads.

### Question 4 

As you have pointed out OpenGL is a large and complicated topic. We have two examples which demonstrate the use of custom visualisations in the FLAME GPU repository - PedestrianLOD and PedestrianNavigation. 

Firstly, You can achieve the desired effect for Fibroblast agents using the default visualisation. If you specify an agent variable named `colour`, and in an agent function (it doesn't matter which) set the `agent->colour` to one of the 8 pre-defined values it will be shaded in the appropriate colour (see [docs::4.7.2](http://docs.flamegpu.com/en/master/flamegpu/simulation.html?highlight=colour#visualisation-mode)). 

From your description I think that you should be able to achieve a reasonable implementation by modifying the default visualisation provided by FLAME GPU. 

To do this, First build your model to generate `src/dynamic/visualisation.cu` (or run `xsltproc` manually). Then, you need to disable the generation of this file to ensure that it is not over-ridden by a rebuild. 

In visual studio this must be done per configuration, in the FLAME GPU section of the project properties menu. 

If you are using the Makefile:

+ Change `CUSTOM_VISUALISATION := 0` to `CUSTOM_VISUALISATION := 1`
+ Uncomment  `TRANSFORM_VISUALISTION_XSLT_DISABLED := 1` to prevent transformation.


Inside `visualisation.cu` there are several sections you will need to duplicate and/or modify to achieve your desired effects. 

The colour of agents in the provided shaders are passed through to the fragment shader (see `fragmentShaderSource`) as an input (`colour`) from the vertex shader (`vertexShaderSource`).

In the vertex shader, this is currently set by a large if-else-if statement based on the `lookup.w` variable, which is agent data passed to OpenGL from CUDA, directly on the GPU (through a process known as OpenGL Interoperability). For your Fibroblast agents you can simply change the r, g and b components of these values to get different colours (note that the fragment shader adds an ambient slightly-red light, which may effect the observed colour).

This data is set by the `output_AGENTNAME_agent_to_VBO` method (i.e `output_TissueBlock_agent_to_VBO`), which will contain a statement along the lines of `vbo[index].w = 1.0;` or `vbo[index].w = agent->colour;`). 
You can set the `vbo[index].w` variable to any floating point value you like, on a per agent basis which is then interacted with by the shader programs. 


I've only touched on a small portion of the GL program, but hopefully enough to make a start.

To achieve TissueBlock agents as cubes which are darker for larger values of damage, you will need to:
+ Pass the damage value to `lookup` via `vbo[index].w`
+ duplicate and modify the vertex shader source to set the appropriate value of `colour` based on the `lookup.w`
+ Duplicate `vertexShader` and `shaderProgram`, allowing you to compile the new vertex shader, and create a second shader program
+ Use the original shaderProgram for Fibroblast agents, and the newer shader program for TissueBlock agents (via `glUseProgram` at the appropriate points, in `display`)
+ Create new VBO (Vertex Buffer Objects) for the vertices and normals of a cube (see `createVBO`)
+ Populate the new VBOs with data for a cube ( see `setVertexBufferData` for the sphere )
+ In the TissueBlock section of `display`, bind the new cube VBOs (`glBindBuffer`) and draw the right number of vertices (`glDrawArrays`)
+ Delete the new GL objects as appropriate in `close`

### Question 5

Running from console mode the output files are placed into the same directory as input files, it is not possible to specify an alternate folder.

**Comment by CiaranWelsh** [comment]
Hi Peter, Thanks for the quick and detailed response. You've given me a lot to work with - some of which is working already. Will keep at it, Cheers, Ciaran

**Comment by ptheywood** [comment]
I've now implemented agent ID generation (see #250) which is also described in the documentation. 

I'll close this issue for now, but feel free to re-open it in the future if you have further questions.
