### ISSUE TITLE
Invalid XML Model File handling

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU#25]
When an XML Model File is incomplete, there is not necessarily a relevant error message produced for the user.

For instance:
If a message partitioning scheme is not specified for a message, the code is generated but will not compile, due to undefined variable `message_<message_name>_count`.

Is the model file validated at all or is it up to the end user to ensure the model is valid?
If not, should the default of `<gpu:partitioningNone></gpu:partitioningNone>` be implied?

**Comment by Robadob** [comment]
More user friendly to provide an intentional compiler error if it's known
to not work.

Presumably where the partitioning select is carried out, just need to add a
check for no partitioning type specified that places an `#error` to inform
the user of their mistake.

**Comment by mondus** [comment]
This is something for version 2 as adding the necessary error handling within the XSLT would be ugly. The expectation for current FLAME GPU is that your model file must validate against the schema to produce a sensible model. Failure to validate should create a build warning or error in the errors dialogue. This doesn't necessarily prevent the rest of the compilation chain though.
