### ISSUE TITLE
Is it possible to make a continuous environment with cyclic features?

### ISSUE THREAD

**Issue by ldeluigi** [FLAMEGPU/FLAMEGPU#265]
I'm trying to implement a model which would benefit from a cyclic environment, that is an environment of dimensions w*h where agents near an edge teleport to the opposite if they get past by it. The problem is I want those agents to see agents near the opposite edge as neighbors.
This model is set in a continuous type of space (i.e. not a cellular automaton).

The only way I found until now is to give up the spatially partitioned messages and to use a custom "neighborhood check" with non partitioned messages, but as you can probably tell performances dropped a lot.

Can you give me some advice? Thank you in advance.

**Comment by ldeluigi** [comment]
Nevermind, I just understood that spacial partitioned take a radius but it's used as a dimension of areas and not as an effective radius that has the center at the position of an agent. Non-partitioned messages seem the only left option.

**Comment by ptheywood** [comment]
Spatial partitioning divides the environment into a grid, where each cell is `radius*radius*radius` in size. 
The moore's neighbourhood of cells surrounding the cell in which an agent lies is accessible to each agent, i.e the cell the agent lies within and the 8 surrounding cells (in a 2D example for simplicity). This guarantees all messages within `radius` of the agent are acessed, and as you point out this wraps in the `x` and `y` dimensions providing a tourus. 

Unfortunately the distance between an individual and the message is not provided, although this is relatively simple to compute, given that the agent and message both require `x`, `y` and `z` variables, althrough wrapping does make the distance calculation a little more complex.
