### ISSUE TITLE
Predator prey model - cannot include grass

### ISSUE THREAD

**Issue by philipparubin** [FLAMEGPU/FLAMEGPU#271]
I cannot run a predator prey model simulation where the predators and preys interact with grass.

I am following the instructions from the tutorial pdf on page 18. The steps I’ve been following are:
  *   compiling xmlGen_IncGrass.cpp
  *   running ./xmlGenEx3 as described with the parameters in the tutorial
  *   going up one to the PreyPredator folder,  make console
  *   going to the Release_Console folder in bin/linux-x64/Release_Console
  *   running PreyPredator in the release console as described
./PreyPredator ../../../examples/PreyPredator/iterations/0.xml 600 0 0
  *   navigating back to the iterations folder to see the output

However the model doesn’t seem to be changing to include grass. When I plot the output it is the same as figure 9
![PreyPredator](https://user-images.githubusercontent.com/52502327/63774307-e5785000-c8d4-11e9-9f31-fcb1e357e812.png)
 but with grass fixed to its initial value of 2000, rather than looking like figure 11. I deleted the .csv file to make sure it was generating this every time and it always produces this with grass fixed to 2000 in every time step.

The 0.xml folder is changing to the new model:
<REPRODUCE_PREY_PROB>0.050000</REPRODUCE_PREY_PROB>
<REPRODUCE_PREDATOR_PROB>0.030000</REPRODUCE_PREDATOR_PROB>
<GAIN_FROM_FOOD_PREDATOR>50</GAIN_FROM_FOOD_PREDATOR>
<GAIN_FROM_FOOD_PREY>75</GAIN_FROM_FOOD_PREY>
<GRASS_REGROW_CYCLES>100</GRASS_REGROW_CYCLES>

I’ve also tried make clean and following the above steps but that produced the same output.

**Comment by ptheywood** [comment]
Would you be able to provide your `XMLModelFile.xml` and `function.c`? 

At a glance it looks like the functions from steps 3.1-3.4 (`grass_output_location`, `grass_eaten`, `prey_eat_or_starve` & `grass_growth`) are not executing / behaving as intended.

**Comment by philipparubin** [comment]
I have emailed you those two files, attaching them here didn't work!
