### ISSUE TITLE
accessing the values of an array variable 

### ISSUE THREAD

**Issue by jiruhameru** [FLAMEGPU/FLAMEGPU#289]
I setup an agent variable as an array in the XMLModelFile as follows:
```
<gpu:variable>
  <type>int</type>
  <name>genes</name>
  <arrayLength>11</arrayLength>
</gpu:variable>

```
When I try to display the array values of the first agent in functions.c, it shows me the first array values from the first 11th agents instead. 
Here is the code I used: 
```
if(agent->id == 1)
{
  int i;
   for (i=0; i<12; i++)
   {
     printf("%d \n", agent->genes[i]);
    }
}
```
I don't know what is wrong, I'd appreciate it if you point me to a way to access the array values for a given agent.

Here is a portion of the iterations.xml: 
```
<?xml version='1.0' encoding='utf-8'?>
<states>
  <itno>0</itno>
  <xagent>
    <name>agent</name>
    <id>1</id>
    <x>-0.766451</x>
    <y>-0.460925</y>
    <z>-0.50777</z>
    <genes>683,866,276,172,878,171,683,866,276,172,878</genes>
    <life_cycle>0</life_cycle>
  </xagent>
  <xagent>
    <name>agent</name>
    <id>2</id>
    <x>-0.158749</x>
    <y>0.167266</y>
    <z>0.821662</z>
    <genes>0,0,0,0,0,1,1,1,0,0,1</genes>
    <life_cycle>0</life_cycle>
  </xagent>
</states>
```

Thanks in advance.

**Comment by ptheywood** [comment]
Agent variable-array data is interleaved for improved memory access pattern on the device, so it is not trivially accessible. It's also not loaded into the `agent` struct, as this would result in very poor performance.

Instead agent array data should be accessed using the generated method `get_AGENTNAME_agent_array_value<T>(T* variable, int element)`, in your case this would be `printf("%d \n", get_agent_agent_array_value<int>(agent->genes, i);`

So for your example above:
```
if(agent->id == 1)
{
  int i;
   for (i=0; i<11; i++)
   {
     printf("%d \n", get_agent_agent_array_value<int>(agent->genes, i);
    }
}
```

Note that for an array length of `11` you should only access indices `0` to `10` (so `i<11`)


This does appear to be completely missing from the online documentation, so I'll open an issue for that to be resolved.
The [Stable Marriage example](https://github.com/FLAMEGPU/FLAMEGPU/tree/master/examples/StableMarriage) demonstrates some use of agent variable arrays.

**Comment by jiruhameru** [comment]
Thanks a lot!
