### ISSUE TITLE
Is there any way to update agent information or global variables through other files at runtime?

### ISSUE THREAD

**Issue by Lucas-Qhy** [FLAMEGPU/FLAMEGPU#291]
I want to couple the output data of my physical model with an agent-based model. So I hope that the agent-based model can read the array data in the physical model's output files during the runtime and update the agent's array variable or global array variable for subsequent interaction between the agents.

Is this possible? Or is there any possible approach to realize my idea?

Thanks in advance!

**Comment by ptheywood** [comment]
>I want to couple the output data of my physical model with an agent-based model. So I hope that the agent-based model can read the array data in the physical model's output files during the runtime and update the agent's array variable or global array variable for subsequent interaction between the agents.
>
>Is this possible? Or is there any possible approach to realize my idea?

[Initialisation functions](https://flamegpu.readthedocs.io/en/master/flamegpu/modelspec.html#initialisation-functions), [Step functions](https://flamegpu.readthedocs.io/en/master/flamegpu/modelspec.html#step-functions) and [Exit functions](https://flamegpu.readthedocs.io/en/master/flamegpu/modelspec.html#exit-functions) are serial CPU-based functions which are defined within the [environment](https://flamegpu.readthedocs.io/en/master/flamegpu/modelspec.html#the-environment) which are executed at the appropriate times during the simulation, and you can perform disk IO from within these functions if required.

+ Init Functions are executed once at the start of the simulation, after values are loaded from the initial states XML file, but before the first step of the simulation
+ Step Functions are executed at the end of each simulation step (including the final step)
+ Exit Functions are executed once at the end of the simulation. 

`argc` and `argv` are not readily accessible to the user in FLAME GPU 1 unfortunately for adding additional command line arguments, but the `const char* getOutputDir()` method can be used to get the path relative to the directory containing the initial states XML file (as this is where XML output files are written), so you can use this to find other files on disk, or you could use your systems environment variables and `getenv` instead.


Once you've read information from disk, you can then set [FLAME GPU environment variables](https://flamegpu.readthedocs.io/en/master/flamegpu/modelspec.html#simulation-constants-global-variables) using the generated functions. I.e. for a `int` environment variable named `A` a method `void set_A(int* value);` would be generated. This can also be used for environment array variables.

You could also use the data to create new agents using the [host agent creation API](https://flamegpu.readthedocs.io/en/master/flamegpu/api.html#agent-creation-from-the-host).

Unfortunately, in released versions of FLAME GPU 1.x there are no methods to directly edit agent data from the host (init, step or exit functions).


We are working on a new major version of FLAME GPU - [FLAME GPU 2](https://github.com/FLAMEGPU/FLAMEGPU2) which includes the ability to edit agents from the host. 
FLAME GPU 2 is not quite ready for general use, as we have a few more breaking changes planned but it's not far off.

**Comment by Lucas-Qhy** [comment]
Thanks a lot!
