### ISSUE TITLE
Problems in running visual mode on Ubuntu

### ISSUE THREAD

**Issue by H-Qin** [FLAMEGPU/FLAMEGPU#302]
I ran EmptyExample_visual on the Ubuntu18.04 in wsl2, and the following errors appeared:
```
FLAMEGPU Visualisation mode
` does not exist using parent directory for output.xml
Initial states: (none)
Output dir: ../../examples/EmptyExample/iterations/
GPU 0: NVIDIA GeForce GTX 1070, SM61, Linux, pciBusId 1
ERROR: Shader Compilation Error
0:3(1): error: duplicate storage qualifier
0:3(1): error: invalid input layout qualifier used
0:9(54): error: syntax error, unexpected ')', expecting '('
ERROR: Shader Program Link Error
OpenGL Error : invalid operation
GPUassert: OS call failed or operation not supported on this OS src/dynamic/visualisation.cu 426
Segmentation fault
```
I ran EmptyExample_console smoothly. I am wondering whether the visual mode can run on my virtual machine. Is the problem due to GPU memory allocation? 

Many thanks!

**Comment by ptheywood** [comment]
The WSL CUDA impelementation [does not currently support OpenGL Interop](https://docs.nvidia.com/cuda/wsl-user-guide/index.html#features-not-yet-supported), so unfortunately the visualisation will not work when using WSL.

If or when OpenGL interop is supported this might start working, but unfortunately that is out of our control.

The visualisation works for native Windows builds via Visual Stuido, or on native Linux installations. 
Using a linux virtual machine may support visualisation, although there may be other issues with using CUDA on a linux VM from a Windows host.
