### ISSUE TITLE
Not possible to run generic code between simulation steps

### ISSUE THREAD

**Issue by mondus** [FLAMEGPU/FLAMEGPU#34]
This is required in some models where rules are based on statistical data from the population. For example birth rate may be a function of the total population density, rather than the perceived local density. Such calculations could be performed by each agent but it makes sense to have host functions which are able perform things like reductions on agent variables.

**Comment by Robadob** [comment]
If you are going to include host functions, it would make sense to also provide host copies of environmental constants (currently the set methods just copy to symbol, without preserving a copy on the host), given they are likely to be accessed/updated from such a method.

Similarly, *might* want to provide a means of creating agents when you have a small number of agents to be created.

These operations seem appropriate (from my understanding) for the model @mozhgan-kch has been implementing.

**Comment by mondus** [comment]
Yes a get function for environment variables is required. I thiought this was already done. Creating agents is a bit more involved and can probably be a feature of v2.0.

**Comment by Robadob** [comment]
>Yes a get function for environment variables is required. I thought this was already done. 

Relevant templates:lines are;

https://github.com/FLAMEGPU/FLAMEGPU/blob/analytics/FLAMEGPU/templates/header.xslt#L450

https://github.com/FLAMEGPU/FLAMEGPU/blob/analytics/FLAMEGPU/templates/simulation.xslt#L472

Neither stores the values on the host and `gpu:constants` doesn't appear in the other templates. So I'd have to assume not. Including them should be fairly trivial though.

Something like

header
```xlst
<xsl:for-each select="gpu:xmodel/gpu:environment/gpu:constants/gpu:variable">
extern<xsl:value-of select="xmml:type"/><xsl:text> h_env_</xsl:text><xsl:value-of select="xmml:name"/><xsl:if test="xmml:arrayLength">[<xsl:value-of select="xmml:arrayLength"/>]</xsl:if>;
</xsl:for-each>
```

simulation (replacing existing code)
```xlst
//host constant declaration
<xsl:value-of select="xmml:type"/><xsl:text> h_env_</xsl:text><xsl:value-of select="xmml:name"/><xsl:if test="xmml:arrayLength">[<xsl:value-of select="xmml:arrayLength"/>]</xsl:if>;

<xsl:for-each select="gpu:xmodel/gpu:environment/gpu:constants/gpu:variable">

//constant setter
void set_<xsl:value-of select="xmml:name"/>(<xsl:value-of select="xmml:type"/>* h_<xsl:value-of select="xmml:name"/>){
	gpuErrchk(cudaMemcpyToSymbol(<xsl:value-of select="xmml:name"/>, h_<xsl:value-of select="xmml:name"/>, sizeof(<xsl:value-of select="xmml:type"/>)<xsl:if test="xmml:arrayLength">*<xsl:value-of select="xmml:arrayLength"/></xsl:if>));
    memcpy(&amp;h_env_<xsl:value-of select="xmml:name"/>, h_<xsl:value-of select="xmml:name"/>,sizeof(<xsl:value-of select="xmml:type"/>)<xsl:if test="xmml:arrayLength">*<xsl:value-of select="xmml:arrayLength"/></xsl:if>);
}

//constant getter
const <xsl:value-of select="xmml:type"/>* get_<xsl:value-of select="xmml:name"/>(){
    return &amp;h_env_<xsl:value-of select="xmml:name"/>;
}
</xsl:for-each>
```

**Comment by ptheywood** [comment]
Exit functions are not executed for visualisation models. 
It's possible to enable them for users who press `Esc` to close the window by adding a call to `cleanup()` to the `keyboard` callback function, however this does not execute when a user closes the window.

Supposedly there is an additional callback function in freeglut/openglut `void glutCloseFunc (void(*)(void) callback)`, however this is not available in the currently included `GL/glut.h`

**Comment by ptheywood** [comment]
File I/O may be beneficial for these functions, it would be useful for the output directory to be available in `functions.c`. 
The simplest way to do this currently is to `extern` the `outputpath` variable by adding to `header.xslt`

    /* IO Variables*/
    extern char inputfile[100];          /**&lt; Input path char buffer*/
    extern char outputpath[100];         /**&lt; Output path char buffer*/
    
Arguably the use of 100 character max paths for command line arg based input should be replaced by a more flexible solution.

**Comment by ptheywood** [comment]
I have an implementation which allows step functions to create agents on the host which works.

Depending on the use case there are two strategies for copying the agent data to the device:

1. A single memcpy of the full SoA data structure
2. A memcpy per array in the SoA data structure

Both approaches have use-cases where they will offer greater performance, however I selected option 2 as in my use-case only a fraction of the `bufferSize` is ever created in a single iteration, even though the model has a large amount of agent variables (`> 20`)

**Comment by mondus** [comment]
@ptheywood Can this go in a pull request to be merged at the next hackathon?

**Comment by ptheywood** [comment]
Yep will do.
