### ISSUE TITLE
FLAME GPU makefile problem with Iceberg

### ISSUE THREAD

**Issue by mondus** [FLAMEGPU/FLAMEGPU#36]
FLAME GPU make files do not work on Iceberg (The Sheffiled Uni HPC facility). The issue resolves around the call to nvcc.

The make file includes the `CUDA_PATH` so that calls to nvcc end up looking like `/usr/local/cuda-7.5/bin/nvcc` rather than just `nvcc`. I think that the former changes the location of where nvcc looks for files to the `bin` directory rather than the makefile location so that the cuda input files are not found. E.g. 

`
/usr/local/cuda-7.5/bin/nvcc -ccbin g++ -I../../common/inc  -m64     -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_52,code=compute_52 -I ../../include/ -I src/model/ -I src/dynamic/ -I src/visualisation/ -I ../../include/GL/ -o io.o -c src/dynamic/io.cu
bash: /usr/local/cuda-7.5/bin/nvcc: No such file or directory
`

From the makefile fails where as modifying the call to 

`
nvcc -ccbin g++ -I../../common/inc  -m64     -gencode arch=compute_20,code=sm_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_37,code=sm_37 -gencode arch=compute_50,code=sm_50 -gencode arch=compute_52,code=sm_52 -gencode arch=compute_52,code=compute_52 -I ../../include/ -I src/model/ -I src/dynamic/ -I src/visualisation/ -I ../../include/GL/ -o io.o -c src/dynamic/io.cu
`
works correctly.

**Comment by ptheywood** [comment]
The `CUDA_PATH` env variable in the makefile is also used to link against the cuda lib files. 

For each make file it should be replace ([source](https://github.com/FLAMEGPU/FLAMEGPU/blob/master/examples/Template/Makefile#L126))

    NVCC          := $(CUDA_PATH)/bin/nvcc -ccbin $(HOST_COMPILER)

with 

    NVCC          := nvcc -ccbin $(HOST_COMPILER)



The only other occurrence of CUDA_PATH is related to: ([source](https://github.com/FLAMEGPU/FLAMEGPU/blob/master/examples/Template/Makefile#L134))


    # build flags
    ifeq ($(TARGET_OS),darwin)
        LDFLAGS += -rpath $(CUDA_PATH)/lib
        CCFLAGS += -arch $(HOST_ARCH)
    else ifeq ($(HOST_ARCH)-$(TARGET_ARCH)-$(TARGET_OS),x86_64-armv7l-linux)
        LDFLAGS += --dynamic-linker=/lib/ld-linux-armhf.so.3
        CCFLAGS += -mfloat-abi=hard
    else ifeq ($(TARGET_OS),android)
        LDFLAGS += -pie
        CCFLAGS += -fpie -fpic -fexceptions
    endif

Honestly I'm not sure we need this as we only support x86_64 hosts at this time. 

If `CUDA_PATH` is removed the readme should be updated to reflect this.

**Comment by mozhgan-kch** [comment]
In the **READ ME (makefiles)**, there is a note on how to set your CUDA_PATH, have you tried that ?

> - If you are using a different version of CUDA compiler, use below command first to change the CUDA_PATH environment variable:
>    export CUDA_PATH=/path/to/CUDA

**Comment by mondus** [comment]
It is not an issue with setting the CUDA_PATH as this is correct and nvcc is found. The issue is that having /path/to/cuda/nvcc rather than just nvcc means that nvcc is looking for the input files (e.g. simulation.cu) in the /path/to/cuda/ location rather than the current working directory.

**Comment by ptheywood** [comment]
Using an absolute path to an executable doesn't change the working directory, so it shouldn't be looking for the files in the `/path/to/cuda` directory.

The error message included in the original issue `bash: /usr/local/cuda-7.5/bin/nvcc: No such file or directory` is stating that the file `nvcc` does not exist at that location. 

I assume that on iceberg cuda is not located in `/usr/local/`, or cuda 7.5 is not available (the latest docs I can find online only suggest 3.2, 4.0 and 6.5 ([source](https://github.com/rcgsheffield/sheffield_hpc/blob/master/parallel/gpu/nvidia_compiler.rst))

On Iceberg with the relevant cuda version loaded what is the output of `which nvcc`?

**Comment by mondus** [comment]
Ok. Totaly correct @ptheywood I thought it was an issue with nvcc not with nvcc not being found. This is because on iceberg nvcc is not in the default location so setting CUDA_PATH fixes this. Not sure why we need to specify CUDA_PATH though. It should be the case that nvcc should be in the users PATH already.
