### ISSUE TITLE
Split into multiple compilation units

### ISSUE THREAD

**Issue by Robadob** [FLAMEGPU/FLAMEGPU#41]
When FLAMEGPU was first setup the 'relocatable device code' option wasn't available, so device functions had to be in the same object as their calling function. This meant that functions.c was made to be included from `simulation.cu`/`fgpu_kernals.cu`

This is a bad idea because it means that any pre-processor macro's defined within `functions.c`, leak into the remainder of `simulations.cu` to be compiled. It also makes partial compilation slower as the entire of `simulation`/`fgpu_kernals`/`functions.c` must be recompiled if you change 1 line in` functions.c`. Also being an include, marked as do not compile can confuse IDE's making them not detect when a recompilation is required.

@mozhgan-kch had this issue this afternoon, and short of noticing the highlighting is off (only going to work in an IDE), or working it out yourself it's a pain to diagnose. In this case the cuda constant symbol was being replaced with a literal at compile time, compiling fine and then throwing runtime err with invalid device symbol.

It might be feasible to rename `functions.c` to `functions.cu` and enable the relocatable device code option, however I expect there will be other minor changes.

**Comment by ptheywood** [comment]
`header.h` should be publicly callable functions, so the required changes to enable this would have to go in say `simulation.h` or similar.

**Comment by ptheywood** [comment]
This would also need a script to automate the upgrade for vcxproj files.

**Comment by Robadob** [comment]
Just tested building with RDC enabled.

To make that compile, it's necessary to `extern` the existing environmental variable declarations found in `header.h`, and then declare them properly elsewhere (e.g. `simulation.cu`).

At this point RDC flame will build, albeit doesn't address the issue here of splitting into multiple compilation units.

**Comment by Robadob** [comment]
I now removed `FLAMEGPU_kernals.cu` from being included by `simulation.cu`, allowing it to compile separately.

In order to allow this to compile, I had to create a header containing `extern`s of the `__constant__` and `texture` vars declared within `FLAMEGPU_kernals.cu`, and similarly prototype all the methods within.

These should be easy to produce from the existing `FLAMEGPU_kernals.xslt`, additionally we will need to prototype all of the `functions.c` methods within this same header (init/step/exit/agent).

This file is an example of what I used to build PedNav, I haven't yet added in the agent functions, allowing functions.c to compile separately.
https://gist.github.com/Robadob/4fd4978f9349c6209d011bfdd4859028

**Comment by Robadob** [comment]
Note the first commit above 	119de92 is orphaned due to a force-push after files were missed.

**Comment by Robadob** [comment]
758194d

Just made an additional commit (linked above, I forgot to tag the issue in msg). This separates off `functions.c` from the `simulation.cu`, `FLAMEGPU_kernals.cu` amalgamation.

I tested this building across all debug versions, there were 5 failures. 4 due to trivial things that are now fixed.

The remaining failure is specific to agent function conditions. SugarScape example utilises a macro define made within `functions.c`, for obvious reasons this can't be relocated to templates.

I suggest that this macro is made into an environmental variable, this will retain its runtime flexibility, and should work naturally, given the condition is tested within a CUDA kernel.

Requesting @mondus approval before making that change.

**Comment by Robadob** [comment]
Just made an additional commit. This separates off `functions.c` from the `simulation.cu`, `FLAMEGPU_kernals.cu` amalgamation.

I tested this building across all debug versions, there were 5 failures. 4 due to trivial things that are now fixed.

The remaining failure is specific to agent function conditions. SugarScape example utilises a macro define made within `functions.c`, for obvious reasons this can't be relocated to templates.

I suggest that this macro is made into an environmental variable, this will retain its runtime flexibility, and should work naturally, given the condition is tested within a CUDA kernel.

Requesting @mondus approval before making that change.

--------

Additionally it becomes necessary to remove `functionfiles` from the xsl specification and to update Linux makefiles to additionally build `functions.cu`.

--------

Next step would be to relocate any device functions called in `functions.cu` to a separate header (random, array reduce, message accessors), this allow them to be inlined at compile time. The performance benefits of this may be negligible, but it's the primary concern of separating CUDA into multiple compilation units.

**Comment by Robadob** [comment]
Just made an additional commit (two shown because I force pushed after a minor mistake, leaving the first one orphaned). This separates off `functions.c` from the `simulation.cu`, `FLAMEGPU_kernals.cu` amalgamation.

I tested this building across all debug versions, there were 5 failures. 4 due to trivial things that are now fixed.

The remaining failure is specific to agent function conditions. SugarScape example utilises a macro define made within `functions.c`, for obvious reasons this can't be relocated to templates.

I suggest that this macro is made into an environmental variable, this will retain its runtime flexibility, and should work naturally, given the condition is tested within a CUDA kernel.

Requesting @mondus approval before making that change.

--------

Additionally it becomes necessary to remove `functionfiles` from the xsl specification and to update Linux makefiles to additionally build `functions.cu`.

--------

Next step would be to relocate any device functions called in `functions.cu` to a separate header (random, array reduce, message accessors), this allow them to be inlined at compile time. The performance benefits of this may be negligible, but it's the primary concern of separating CUDA into multiple compilation units.

**Comment by Robadob** [comment]
Spoke with @mondus , need to adjust agent array functions to replace currently templated system.

**Comment by Robadob** [comment]
d9832f7

I've now updated agent array functions to provide transparent access to arrays via operator overloading. This is a breaking change, but produces much cleaner code. This also fixes the mistake that I made in a prior commit for handling array accessors with RDC.

**Comment by Robadob** [comment]
Still think I need to address struct (with array) allocation as I did in polynav work.

**Comment by ptheywood** [comment]
As @Robadob  with his work `rdc` can have significant performance implications, and we are progressing with FLAME GPU 2, this can be closed for now as wontfix.

**Comment by Robadob** [comment]
For clarity if this gets dug up in future. Testing showed that certain kernels when compiled with `rdc=true` and no other changes, would inflate register usage by as much as 75%. An easy example of this is changing the flag and rebuilding the CUDA particles sample code.

Inflating register usage by this much has obvious knock on effects for occupancy with large kernels, and hence can harm performance quite significantly.

The assumption is that it's tied to use of device kernels, as if kernels are in separate compile time objects it can't perform whole run-time optimisation/register re-use. However even when they are in the same compile time object we still get the rogue register inflation if `rdc` is enabled.

This testing was carried out using CUDA 8.0, haven't had time to test this with CUDA 9.1 to ensure it's still the case and query/report it as a bug. Notably the documentation's explanation of `rdc` does not suggest about register usage inflation.
