### ISSUE TITLE
Issues with negative timestep on Pedestrian Navigation

### ISSUE THREAD

**Issue by coolmule0** [FLAMEGPU/FLAMEGPU#52]
![negativepednav](https://cloud.githubusercontent.com/assets/13734115/20966781/f377ff2c-bc73-11e6-853f-e5aee8eefbd3.png)

**Comment by ptheywood** [comment]
Simple fix is to clamp the value of `Time Scalar` to be non-negative (maybe even non-zero?)  in the custom visualisation, or use an `unsigned int` (and prevent underflow).

**Comment by ptheywood** [comment]
This will need fixing in both pedestrian models (and non-public models)
