### ISSUE TITLE
[question] FLAMEGPU cluster configuration

### ISSUE THREAD

**Issue by eze1981** [FLAMEGPU/FLAMEGPU#55]
Hi,
Is it possible to run FLAMEGPU on a GPU cluster environment (nodes connected via InfiniBand)?

**Comment by mondus** [comment]
Absolutely. To run console examples you simply need to clone the code and ensure you have gcc and nvcc installed (with an appropriate graphics driver). There is an example for the Sheffield cluster on our docs page.

[http://docs.hpc.shef.ac.uk/en/latest/parallel/gpu/FLAMEGPU.html](http://docs.hpc.shef.ac.uk/en/latest/parallel/gpu/FLAMEGPU.html)

Note: FLAME GPU is only single GPU device (which is enough to simulate very large models).  Visualisation requires a HPC environment with a virtual GL setup. This is experimental although we have a working version of this at Sheffield.

**Comment by eze1981** [comment]
Hi @mondus,

when you say that "FLAME GPU is only single GPU device", I understand that:
1. no make sense to have more than 1 GPU per node
2. no make sense to have more than 1 node, because given a simulation I'm not going to be able to distribute the GPU load between nodes (1 GPU per node)

Is that correct?

Thank you,
Ezequiel

**Comment by mondus** [comment]
Hi @eze1981 

You are correct that there is no support for a **single model** to use either 1) multiple GPUs per host or 2) distributed GPUs. As you point out, this would require load balancing. This is something that we are working on for future versions which will cover both cases for very large models.

Of course if you want to run different simulations (or same simulation with different parameters) you could use different GPUs on you cluster to do this in parallel. Lots of users write scripts to do this when running large numbers of experiments.

**Comment by eze1981** [comment]
thank you
