### ISSUE TITLE
Limitations on Spatially Partitioned Messaging dimensions

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU#63]
Windows imposes limits on the size of statically allocated data. For 32bit and 64bit windows this is limited to `2GB` ([source](https://software.intel.com/en-us/articles/memory-limits-applications-windows)).

The number of bins required for spatially partitioned messaging is dependant upon the bounds and radius. If the combination of environment bounds and radius result in a significant number of bins being required (approx `536,870,912` bins, or roughly an `812*812*812` cube ) then the application will not compile.
This should not be a problem for FLAMEGPU2 as dynamically allocated memory can  be up to `8TB` on Windows x64.

Furthermore, the use of `cudaBindTexture` in spatially partitioned messaging imposes an additional limit (device dependant) at runtime.
The total number of elements in a linear address range cannot exceed ` cudaDeviceProp::maxTexture1DLinear[0]` ([source](http://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TEXTURE.html#group__CUDART__TEXTURE_1g8eeaa2b65b8b76ab155014a8de6838b9)), which for a Geforce GTX Titan X is `134217728` texels ([source](https://github.com/NVIDIA/DIGITS/issues/1294#issuecomment-266257632)).
In practice this limits the number of bins in spatially partitioned messaging to `512*512*512`.

**Comment by mondus** [comment]
Great spot. A bin with `512*512*512` would require 1GB of memory anyway so chances are that any model would be close to reaching memory limitations. Still can be fixed in version 2.
