### ISSUE TITLE
Pointer swaps for agent xmachine_memory_*_lists

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU#65]
@mondus suggested that under certain conditions it should be possible to avoid using `append_<agentname>_Agents` kernels to move agents from one state to another during agent functions.

+ If `currentState == nextState`, it should be safe to do a simple pointer swap.
    + If there are no function conditions and `reallocate==false`
    + Global conditions should be fine.
+ If there is a state change (`currentState != nextState`), and the population of the `nextState == 0` then a pointer swap should be possible
    + If there are no function conditions and `reallocate == false`.
    + Possible edge case: multiple agent functions in the same layer have the same `nextState`

+ If the 

+ When `reallocate == true`, it may be possible to still do the pointer swap
     + It depends on the reallocation process, needs to be looked into.
+ The case of functions which create agents needs to be considered.

The cost of the append function is relatively small compared to typical agent functions, however, for large agent populations with large numbers of agent parameters the cost will be insignificant. 
For the keratinocyte model with only `1024` agents and the append kernel only takes `~4μs` per invocation plus any kernel sync overheads, however this is a very small agent population.

**Comment by coolmule0** [comment]
If `currentState == nextState && reallocate == false && condition == false && globalCondition == false` sorted in c1a9259706ec0f89fa35d2e32b29cddf6eb3293d. Covers my use case

**Comment by ptheywood** [comment]
ed4dd38 addresses an issue where if agents are output by an agent function then the pointer swap cannot be used (as the swap memory is used to store data about the new agents).
