### ISSUE TITLE
Update FLAME GPU Documentation

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU#66]
The documentation needs to be updated with recent features and developments including:

+ [ ] Instrumentation constants
+ [ ] Limitations of statically allocated memory (2GB limit on windows) which effects agent populations, message list size and the number of bins available for spatially partitioned messaging.
+ [x] The current Linux build process
+ [ ] Step Functions 
+ [ ] Analytics functions such as reductions
    + [ ] Including that these are not available for agent variable arrays
+ [ ] Upcoming host-based agent creation (init and step functions)
+ [ ] `PAUSE_ON_START` in `visualisation.h`

etc.

https://github.com/FLAMEGPU/FLAMEGPU_TechnicalReport

**Comment by mondus** [comment]
Documentation is now hosted on github but also integrated with sharelatex. Contributions should be made by pull requests or tracked changes respectively.

**Comment by ptheywood** [comment]
https://github.com/FLAMEGPU/FLAMEGPU_TechnicalReport for future reference.

**Comment by mondus** [comment]
Anyone know of a good method to auto generate HTML docs from Latex? sharethedocs is markdown only. @ptheywood @mikecroucher ?

**Comment by ptheywood** [comment]
For now update PDF for 1.5.

In the future (post 1.5) move to a nice markdown(?) based system.

**Comment by ptheywood** [comment]
This is now being moved to a ReStructuredText based system by @mondus.

**Comment by ptheywood** [comment]
Documentation is now stored in [flamegpu/docs](github.com/flamegpu/docs), and hosted at [docs.flamegpu.com](http://docs.flamegpu.com)

We may wish to:
+ [ ] Remove the technical report from the repository? **OR** Replace the technical report with a pdf of the new documentatiojn
+ [ ] Update the README to point to the documentation.

**Comment by ptheywood** [comment]
This issue has been replaced by FLAMEGPU/docs#4
