### ISSUE TITLE
Upgrade projects + makefiles to use CUDA 8.0 by default

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU#67]
CUDA 8.0 was announced over a year ago, and provides significantly improved compilation time compared to 7.5.

Additionally CUDA 9.0 has been announced (although with no public release date, likely Q3/Q4 2017 to support Volta GPUs in DGX-1v/DGX Station etc)

Visual studio project files, and linux Makefiles should be modified to default to 8.0, or the latest installed version if possible (Makefiles).

**Comment by mondus** [comment]
Agreed. This should also include upgrading to VS2015.

**Comment by ptheywood** [comment]
CUDA 8.0 issues warnings for SM_20 and SM_21 as they are deprecated.

When rebuilding in Visual Studio, `nvcc` is invoked with the `-clean` flag to delete temporary files, without specifying any target architectures. This causes the default architectures to be used, which raises the warning.

This seems to be controlled by the CUDA 8.0 visual studio integration files, rather than anything in FLAME GPU itself. 
`-Wno-deprecated-gpu-targets` can be used to suppress the warnings via `Solution Properties > CUDA C/C++ > Command Line > Additional Options` however this would also suppress the warning for any users targeting the deprecated architectures.

**Comment by ptheywood** [comment]
@mondus Which SM's do we want to be included by default in the updated project files?

Currently we use 

    compute_20,sm_20;compute_30,sm_30;compute_35,sm_35;compute_50,sm_50

Obviously we want to add `sm_60` for full pascal support.

The main question is should we remove `sm_20` as it is deprecated or not?

**Comment by ptheywood** [comment]
Used `sed` to make these changes via:

```
find ./examples -type f -name "*.vcxproj" -exec sed -i 's/ToolsVersion="12.0"/ToolsVersion="14.0"/g' {} +
find ./examples -type f -name "*.vcxproj" -exec sed -i 's/<PlatformToolset>v120<\/PlatformToolset>/<PlatformToolset>v140<\/PlatformToolset>/g' {} +
find ./examples -type f -name "*.vcxproj" -exec sed -i 's/CUDA 7.0./CUDA 8.0./g' {} +
find ./examples -type f -name "*.vcxproj" -exec sed -i 's/compute_20,sm_20;compute_30,sm_30;compute_35,sm_35;compute_50,sm_50/compute_30,sm_30;compute_35,sm_35;compute_50,sm_50;compute_60,sm_60/g' {} +

find ./examples -type f -name "Makefile" -exec sed -i 's/cuda-7.5/cuda-8.0/g' {} +
find ./examples -type f -name "Makefile" -exec sed -i 's/20 30 35 37 50 52/30 35 37 50 60/g' {} +
```
https://gist.github.com/ptheywood/0a73ebb170731f46f0efdfb60fa5d78d

**Comment by ptheywood** [comment]
Opening The viles in VS 2015 does add additional changes to the solution files it seems, which should be  included.

**Comment by ptheywood** [comment]
ef492f1 adds the changes from opening each solution in VS 2015

**Comment by willfurnass** [comment]
Can't compile examples for current HEAD of master (`e2c2c5b`) with CUDA 9.0.176 as `compute_20` no longer supported.  

```
nvcc fatal   : Unsupported gpu architecture 'compute_20'
```

**Comment by ptheywood** [comment]
The current HEAD of master is probably still targeting CUDA 7 or 7.5, with our next release moving the visual studio project files to CUDA 8 (so far).  Included in this update is the removal of SM20 from the default list of architectures being built, as it was deprecated for CUDA 8. 

We have not yet tested FLAME GPU using CUDA 9.0, however the issue of  SM20 and SM21 being removed *should* be the only reason it won't compile.

CUDA 9.0 will potentially produce many new warnings regarding deprecated functions, which we should attempt to resolve.

The `rc1.5/alternate-makefiles` branch (currently 3022b8a) includes heavily-revised makefiles which *should* only builds for SM30 and above, so should build with CUDA 9, though this is untested.

**Comment by mondus** [comment]
Aim is for CUDA 9
