### ISSUE TITLE
Support loading of environment constants from initial states file

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU#70]
To avoid users having to create init functions, which set the initial value of environment constants either to a fixed value or by loading from disk manually, it would be beneficial to have this as loading from the initial states XML file (`0.xml`).

All required information to handle this is available at compile time from `XMLModelFile.xml` and can be built into `io.cu`.
This would be much simpler to support using @Robadob 's updated XML handling branch mentioned in #16

**Comment by ptheywood** [comment]
If not fixed via rapidxml branch, must be manually added to `io.xslt`

**Comment by ptheywood** [comment]
Additionally, if the rapidXML branch is not adopted for agent state output, then types other than `float`, `int` and `double` will need incorporating into the output (and input), i.e. `unsigned int` which currently raises a warning.

**Comment by ptheywood** [comment]
Additionally, environmental variables are allowed `<defaultValue>` in the schema and is shown in the examples, however this value is not used.
This should be relatively simple to fix, however loading from the initial states file also still required.

```
<gpu:constants>
    <gpu:variable>
        <type>int</type>
        <name>const_variable</name>
        <description>none</description>
        <defaultValue>1</defaultValue>
    </gpu:variable>
    <gpu:variable>
        <type>int</type>
        <name>const_array_variable</name>
        <description>none</description>
        <arrayLength>5</arrayLength>
    </gpu:variable>
</gpu:constants>
```

**Comment by Robadob** [comment]
Above commit has now been merged into rc1.5. Paul apparently said he'll handle env loading from init xml.

**Comment by mondus** [comment]
Other types moved to new issue

**Comment by mondus** [comment]
Done. FLAME GPU docs also updated on sharelatex.
