### ISSUE TITLE
Vector data types for agent variables

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU#86]
Allow float2/glm::vec2 etc for agent variables. 

probably include the glm namespace so we can use the vec2 in the XMLModelFile.XML.

**Comment by mondus** [comment]
Also requires #101

**Comment by mondus** [comment]
@ptheywood Vector types for agents are now added with support for other basic types (unsigned int etc). See RC1.5/VectorTypes branch. Vector types cannot however be used for messages without a complete rewrite of message reading to avoid use of textures. I very much want to avoid this. Given @Robadob recent results the suggestion is that actually vector types will hinder message performance anyway.

Pete could you give this a once over before I put in a pull request. I suggest we remove the TypesTest example when we merge.
