### ISSUE TITLE
1.5 Release miscellaneous tasks

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU#87]
Need to update the readme etc for the new release

+ [x] Resolve and close all relevant issues.
+ [x] Update Readme
    + [x] Convert to markdown
    + [x] Release 1.5 full changelog
    + [x] Incorporate linux makefile instructions into primary readme
+ [x] rename licence to LICENCE etc.
+ [x] Add descriptions of all the examples
+ [x] Test on Windows + Linux
+ [x] Rewrite history purging large XML files (#140) and tracked binaries (#64)
+ [x] Source code formatting
    + Montecarlo XML files for instance
    + [x] XMLModelFile.xml vai XMLlint #230
+ [x] Update all comments referencing FLAME GPU v1.4.0 and CUDA 6
    +  ~~Write a bash/bat/python script to do this across the repo, to simplify future updates~~
+ [x] Build archives and tag the release
+ [x] Update documentation repository, to reflect 1.5.0
    + flamegpu/docs#17
+ [x] Update sheffield HPC documentation to reflect 1.5.0. 
    + http://docs.hpc.shef.ac.uk/en/latest/sharc/software/libs/FLAMEGPU.html
+ [x] Update FLAME GPU tutorial to use 1.5.0

**Comment by ptheywood** [comment]
I've outlined a couple of new structures for a markdown readme inspired by other readmes on github

+ [v1](https://gist.github.com/ptheywood/e890a4609cdf7701cf6ea32162f241a2)
+ [v2](https://gist.github.com/ptheywood/9acaf7070bc6e72c741250058295edde)

Thoughts? @mondus @mozhgan-kch @Robadob 
I'm leaning towards v2, though nothing is set in stone (hence gists)

**Comment by mondus** [comment]
I vote for v2

**Comment by ptheywood** [comment]
I've added the V2 outline to the rc1.5/readme branch. I will continue to work on this as I go.

@mozhgan-kch  would you be able to incorportate the makefile document into this, and any other additions you feel necessary?

@twinkarma when you have modified the command line arguments would you be able to update the usage section?

**Comment by ptheywood** [comment]
This will want to be rebasing before merge, as other changes to the makefile readme will likely cause a conflict.

**Comment by mondus** [comment]
Comments referencing FLAME GPU v1.4.0 and CUDA 6 have been updated in the templates within #160 . Now references version 1.5.X so this only needs updating for major version releases. I have also simplified the (C) statement to remove the date.

**Comment by ptheywood** [comment]
Sheffield HPC docs will be updated when rcgsheffield/sheffield_hpc#826 is merged.
