### ISSUE TITLE
PedestrianNav: GlobalsController.cpp getStateExitN() fn's return incorrect type

### ISSUE THREAD

**Issue by Robadob** [FLAMEGPU/FLAMEGPU#95]
The functions `getStateExit1()` to `getStateExit7()` are all of return type `float`, however the variables returned are all integers.

It's likely a harmless mistake, but a little misleading at a glance.

**Comment by ptheywood** [comment]
The flame model has the exit state variables as integers:
```
extern void set_EXIT1_STATE(int* h_STATE);
```
And the globally scoped host variables are integers.
```
int exitState1 = INITIAL_EXIT1_STATE;
```
But they are used as booleans.
```
void toggleStateExit1()
{
	exitState1 = !exitState1;
	set_EXIT1_STATE(&exitState1);
}
```
And the getter uses floats
```
float getStateExit1()
{
	return exitState1;
}
```

In practice, the getter methods are never used, so this has not raised any issues. If they were used a warning would have been rasied about assigning a float to an int i.e

```
int x = getStateExit1();
```
These functions either want to be removed, or the return type should be changed to an int.

**Comment by ptheywood** [comment]
9974194 updates the return type to int
