### ISSUE TITLE
Uninitialised `count` in Boids Model(s)

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/FLAMEGPU#96]
The `count` variable used to track the number of `location_message`s parsed in the `inputdata` agent function of the boids model is not initialised.

This is undefined.

+ [x] [Boids_BruteForce/src/model/functions.c:100](https://github.com/FLAMEGPU/FLAMEGPU/blob/master/examples/Boids_BruteForce/src/model/functions.c#L100)
+ [x] [Boids_Partitioning/src/model/functions.c:99](https://github.com/FLAMEGPU/FLAMEGPU/blob/master/examples/Boids_Partitioning/src/model/functions.c#L99)

**Comment by ptheywood** [comment]
@mozhgan-kch Is this ready to be merged? If so can you submit a PR against release 1.5?

**Comment by mozhgan-kch** [comment]
RFR. Done
